# Generated by Django 6.0 on 2025-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_hour',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
