# Generated by Django 6.0 on 2025-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0003_alter_vehicle_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
