# Generated by Django 6.0 on 2025-12-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0004_alter_vehicle_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(default=2, help_text='Number of seats'),
        ),
    ]
