# Generated by Django 6.0 on 2025-12-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0005_vehicle_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats'),
        ),
    ]
