# Generated by Django 6.0 on 2025-12-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0006_remove_damagereport_damage_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damage_reported', 'Damage Reported'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
