# Generated by Django 6.0 on 2025-12-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('handover_uploaded', 'Handover Uploaded'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damage_reported', 'Damage Reported'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
