# Generated by Django 6.0 on 2025-12-31 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0008_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclehandoverphoto',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vehiclehandoverphoto',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='vehiclehandoverphoto',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vehiclehandoverphoto',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehiclehandoverphoto',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_photos', to='wheelzy_app.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('handover_uploaded', 'Handover Uploaded'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damage_reported', 'Damage Reported'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wheelzy_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='wheelzy_app.booking'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_damages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='wheelzy_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
