# Generated by Django 6.0 on 2025-12-31 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0009_rename_uploaded_at_vehiclehandoverphoto_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_damages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='wheelzy_app.vehicle'),
        ),
    ]
