# Generated by Django 6.0 on 2026-01-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='security_deposit',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
