# Generated by Django 6.0 on 2026-01-05 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0019_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damage_reported', 'Damage Reported'), ('cancelled', 'Cancelled')], default='payment_pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheelzy_app.vehicle'),
        ),
    ]
