# Generated by Django 6.0 on 2026-01-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0020_booking_is_paid_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_paid',
            new_name='is_rent_paid',
        ),
    ]
