# Generated by Django 6.0 on 2026-01-06 06:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0022_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagephoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='damage_photos'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='aadhaar_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhaar'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='driving_license_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhaar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photos'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vehicle_images'),
        ),
        migrations.AlterField(
            model_name='vehiclehandoverphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='handover_photos'),
        ),
    ]
