# Generated by Django 6.0 on 2026-01-09 07:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0025_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='driving_license_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='licence'),
        ),
    ]
