# Generated by Django 6.0 on 2026-01-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0026_alter_userdocument_driving_license_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damage_reported', 'Damage Reported'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='payment_pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processed', 'Processed'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='wheelzy_app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
