# Generated by Django 6.0 on 2026-09-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelzy_app', '0029_aichathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIChatHistory',
        ),
    ]
