import random

def generate_otp():
    return str(random.randint(100000, 999999))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib import colors
from io import BytesIO
from django.conf import settings
import os
from reportlab.pdfgen import canvas

def generate_booking_invoice(booking):
    buffer = BytesIO()
    pdf = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Logo
    logo_path = os.path.join(settings.BASE_DIR, "static/images/wheelzy1.png")
    if os.path.exists(logo_path):
        logo = Image(logo_path, width=4*cm, height=4*cm)
        elements.append(logo)

    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>Wheelzy Booking Invoice</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    booking_date = booking.ordered_at.strftime("%d %b %Y, %I:%M %p")

    # GST Calculation
    gst_rate = 0.18
    base_amount = booking.total_price / (1 + gst_rate)
    cgst = base_amount * 0.09
    sgst = base_amount * 0.09

    data = [
        ["Booking ID", booking.id],
        ["Customer", booking.user.username],
        ["Email", booking.user.email],
        ["Vehicle", booking.vehicle.vehicle_name],
        ["Number Plate", booking.vehicle.number_plate],
        ["Booking Date", booking_date],
        ["Rental Period",
         f"{booking.start_time.strftime('%d %b %Y %I:%M %p')} - {booking.end_time.strftime('%I:%M %p')}"],
        ["Base Amount", f"₹{base_amount:.2f}"],
        ["CGST (9%)", f"₹{cgst:.2f}"],
        ["SGST (9%)", f"₹{sgst:.2f}"],
        ["Total Paid", f"₹{booking.total_price:.2f}"],
    ]

    table = Table(data, colWidths=[6*cm, 8*cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph("Thank you for choosing <b>Wheelzy</b>. Ride safe!", styles["Normal"])
    )

    pdf.build(elements)
    buffer.seek(0)
    return buffer


def generate_owner_payout_invoice(booking):
    buffer = BytesIO()
    pdf = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>Wheelzy Owner Payout Statement</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    platform_commission = booking.total_price * 0.10
    owner_amount = booking.total_price * 0.90

    data = [
        ["Booking ID", booking.id],
        ["Vehicle", booking.vehicle.vehicle_name],
        ["Owner", booking.vehicle.owner.username],
        ["Booking Date", booking.ordered_at.strftime("%d %b %Y, %I:%M %p")],
        ["Total Rent", f"₹{booking.total_price:.2f}"],
        ["Platform Fee (10%)", f"₹{platform_commission:.2f}"],
        ["Owner Payout", f"₹{owner_amount:.2f}"],
    ]

    table = Table(data, colWidths=[6*cm, 8*cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph("This document is system generated by Wheelzy.", styles["Normal"])
    )

    pdf.build(elements)
    buffer.seek(0)
    return buffer

